<a href="https://colab.research.google.com/github/zharfanw/dsp_series_python/blob/main/DSP_Series_1_Intro_and_Tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DSP Series 1 : Intro and tools
*By Muhammad Zharfan Wiranata*
<br><br>
We need tools for doing signal processing. And choosen Google golab with its Python. So there are tools we needed

## [Numpy](https://numpy.org/doc/stable/index.html)


NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

The point is is like MATLAB array for python. It has its [complete guide](https://numpy.org/doc/stable/user/absolute_beginners.html) for beginner. So on this notebook i just share some usefull snippet code for you and me by my Experience.


### Snippet : Create and Append Numpy Array

Create Empty Array and append it

In [6]:
import numpy as np

## First we create an empty numpy/filled array
a = np.array([])

print("Variable a before append: ",end="")
print(a)

for i in range(10):
  # print(i)
  a = np.append(a,i*3)

print("Variable a after append: ",end="")
print(a)

Variable a before append: []
Variable a after append: [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]


Filled Array and Append it

In [10]:
## First we create an empty numpy/filled array
a = np.array([1,2,4])

print("Variable a before append: ",end="")
print(a)

for i in range(10):
  # print(i)
  a = np.append(a,i*3)

print("Variable a after append: ",end="")
print(a)

Variable a before append: [1 2 4]
Variable a after append: [ 1  2  4  0  3  6  9 12 15 18 21 24 27]


Filled 2D array and append it

In [14]:
## First we create an empty numpy/filled array
# a = np.array([[1,2,4]])
a = np.array([[1,2,4],[5,6,7]])


print("Variable a before append: ",end="")
print(a)

for i in range(10):
  # print(i)
  a = np.append(a,[[i*3,i*4,i*5]], axis=0)

print("Variable a after append: ",end="")
print(a)

Variable a before append: [[1 2 4]
 [5 6 7]]
Variable a after append: [[ 1  2  4]
 [ 5  6  7]
 [ 0  0  0]
 [ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]
 [12 16 20]
 [15 20 25]
 [18 24 30]
 [21 28 35]
 [24 32 40]
 [27 36 45]]


### Snippet : Create Time domain 

In [22]:
first_time = 0 # seconds
last_time = 10 # seconds

fs = 0.1

time = np.arange(first_time,last_time,fs)

print(time)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


## [Pandas](https://pandas.pydata.org/)


Pandas is like table for data processing. It can handle very big big data. And can handle more variant data type in a row. Furthermore, we can go to [this guide](https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html) for complete guide.



like numpy above, we just share some snippet code that i always used in my project

### Snippet : Create and Append data in pandas

Append row

Append Column

Cleaning Zero Data